-- Ensure every library category has full system field definitions, including audit/review columns.

INSERT INTO library_field_definitions (id, category, key, label, value_type, is_system, is_visible_in_viewer, created_by_user_id)
VALUES
  ('fld-contact-family', 'contact', 'family', 'Family', 'text', TRUE, TRUE, 'system-user'),
  ('fld-contact-isactive', 'contact', 'isActive', 'Active', 'text', TRUE, TRUE, 'system-user'),
  ('fld-contact-stockstatus', 'contact', 'stockStatus', 'Stock status', 'text', TRUE, FALSE, 'system-user'),
  ('fld-contact-compatibilityhints', 'contact', 'compatibilityHints', 'Compatibility hints', 'text', TRUE, FALSE, 'system-user'),
  ('fld-contact-createdbyuserid', 'contact', 'createdByUserId', 'Created by', 'text', TRUE, TRUE, 'system-user'),
  ('fld-contact-createdat', 'contact', 'createdAt', 'Created at', 'text', TRUE, TRUE, 'system-user'),
  ('fld-contact-isreviewed', 'contact', 'isReviewed', 'Reviewed', 'text', TRUE, TRUE, 'system-user'),
  ('fld-contact-reviewedbyuserid', 'contact', 'reviewedByUserId', 'Reviewed by', 'text', TRUE, TRUE, 'system-user'),
  ('fld-contact-reviewedat', 'contact', 'reviewedAt', 'Reviewed at', 'text', TRUE, TRUE, 'system-user'),
  ('fld-contact-lasteditedbyuserid', 'contact', 'lastEditedByUserId', 'Last editor', 'text', TRUE, TRUE, 'system-user'),
  ('fld-contact-lasteditedat', 'contact', 'lastEditedAt', 'Last edited at', 'text', TRUE, TRUE, 'system-user'),

  ('fld-sleeve-tube-braid-family', 'sleeve-tube-braid', 'family', 'Family', 'text', TRUE, TRUE, 'system-user'),
  ('fld-sleeve-tube-braid-isactive', 'sleeve-tube-braid', 'isActive', 'Active', 'text', TRUE, TRUE, 'system-user'),
  ('fld-sleeve-tube-braid-stockstatus', 'sleeve-tube-braid', 'stockStatus', 'Stock status', 'text', TRUE, FALSE, 'system-user'),
  ('fld-sleeve-tube-braid-compatibilityhints', 'sleeve-tube-braid', 'compatibilityHints', 'Compatibility hints', 'text', TRUE, FALSE, 'system-user'),
  ('fld-sleeve-tube-braid-createdbyuserid', 'sleeve-tube-braid', 'createdByUserId', 'Created by', 'text', TRUE, TRUE, 'system-user'),
  ('fld-sleeve-tube-braid-createdat', 'sleeve-tube-braid', 'createdAt', 'Created at', 'text', TRUE, TRUE, 'system-user'),
  ('fld-sleeve-tube-braid-isreviewed', 'sleeve-tube-braid', 'isReviewed', 'Reviewed', 'text', TRUE, TRUE, 'system-user'),
  ('fld-sleeve-tube-braid-reviewedbyuserid', 'sleeve-tube-braid', 'reviewedByUserId', 'Reviewed by', 'text', TRUE, TRUE, 'system-user'),
  ('fld-sleeve-tube-braid-reviewedat', 'sleeve-tube-braid', 'reviewedAt', 'Reviewed at', 'text', TRUE, TRUE, 'system-user'),
  ('fld-sleeve-tube-braid-lasteditedbyuserid', 'sleeve-tube-braid', 'lastEditedByUserId', 'Last editor', 'text', TRUE, TRUE, 'system-user'),
  ('fld-sleeve-tube-braid-lasteditedat', 'sleeve-tube-braid', 'lastEditedAt', 'Last edited at', 'text', TRUE, TRUE, 'system-user'),

  ('fld-label-family', 'label', 'family', 'Family', 'text', TRUE, TRUE, 'system-user'),
  ('fld-label-isactive', 'label', 'isActive', 'Active', 'text', TRUE, TRUE, 'system-user'),
  ('fld-label-stockstatus', 'label', 'stockStatus', 'Stock status', 'text', TRUE, FALSE, 'system-user'),
  ('fld-label-compatibilityhints', 'label', 'compatibilityHints', 'Compatibility hints', 'text', TRUE, FALSE, 'system-user'),
  ('fld-label-createdbyuserid', 'label', 'createdByUserId', 'Created by', 'text', TRUE, TRUE, 'system-user'),
  ('fld-label-createdat', 'label', 'createdAt', 'Created at', 'text', TRUE, TRUE, 'system-user'),
  ('fld-label-isreviewed', 'label', 'isReviewed', 'Reviewed', 'text', TRUE, TRUE, 'system-user'),
  ('fld-label-reviewedbyuserid', 'label', 'reviewedByUserId', 'Reviewed by', 'text', TRUE, TRUE, 'system-user'),
  ('fld-label-reviewedat', 'label', 'reviewedAt', 'Reviewed at', 'text', TRUE, TRUE, 'system-user'),
  ('fld-label-lasteditedbyuserid', 'label', 'lastEditedByUserId', 'Last editor', 'text', TRUE, TRUE, 'system-user'),
  ('fld-label-lasteditedat', 'label', 'lastEditedAt', 'Last edited at', 'text', TRUE, TRUE, 'system-user'),

  ('fld-strain-relief-family', 'strain-relief', 'family', 'Family', 'text', TRUE, TRUE, 'system-user'),
  ('fld-strain-relief-isactive', 'strain-relief', 'isActive', 'Active', 'text', TRUE, TRUE, 'system-user'),
  ('fld-strain-relief-stockstatus', 'strain-relief', 'stockStatus', 'Stock status', 'text', TRUE, FALSE, 'system-user'),
  ('fld-strain-relief-compatibilityhints', 'strain-relief', 'compatibilityHints', 'Compatibility hints', 'text', TRUE, FALSE, 'system-user'),
  ('fld-strain-relief-createdbyuserid', 'strain-relief', 'createdByUserId', 'Created by', 'text', TRUE, TRUE, 'system-user'),
  ('fld-strain-relief-createdat', 'strain-relief', 'createdAt', 'Created at', 'text', TRUE, TRUE, 'system-user'),
  ('fld-strain-relief-isreviewed', 'strain-relief', 'isReviewed', 'Reviewed', 'text', TRUE, TRUE, 'system-user'),
  ('fld-strain-relief-reviewedbyuserid', 'strain-relief', 'reviewedByUserId', 'Reviewed by', 'text', TRUE, TRUE, 'system-user'),
  ('fld-strain-relief-reviewedat', 'strain-relief', 'reviewedAt', 'Reviewed at', 'text', TRUE, TRUE, 'system-user'),
  ('fld-strain-relief-lasteditedbyuserid', 'strain-relief', 'lastEditedByUserId', 'Last editor', 'text', TRUE, TRUE, 'system-user'),
  ('fld-strain-relief-lasteditedat', 'strain-relief', 'lastEditedAt', 'Last edited at', 'text', TRUE, TRUE, 'system-user'),

  ('fld-module-family', 'module', 'family', 'Family', 'text', TRUE, TRUE, 'system-user'),
  ('fld-module-isactive', 'module', 'isActive', 'Active', 'text', TRUE, TRUE, 'system-user'),
  ('fld-module-stockstatus', 'module', 'stockStatus', 'Stock status', 'text', TRUE, FALSE, 'system-user'),
  ('fld-module-compatibilityhints', 'module', 'compatibilityHints', 'Compatibility hints', 'text', TRUE, FALSE, 'system-user'),
  ('fld-module-createdbyuserid', 'module', 'createdByUserId', 'Created by', 'text', TRUE, TRUE, 'system-user'),
  ('fld-module-createdat', 'module', 'createdAt', 'Created at', 'text', TRUE, TRUE, 'system-user'),
  ('fld-module-isreviewed', 'module', 'isReviewed', 'Reviewed', 'text', TRUE, TRUE, 'system-user'),
  ('fld-module-reviewedbyuserid', 'module', 'reviewedByUserId', 'Reviewed by', 'text', TRUE, TRUE, 'system-user'),
  ('fld-module-reviewedat', 'module', 'reviewedAt', 'Reviewed at', 'text', TRUE, TRUE, 'system-user'),
  ('fld-module-lasteditedbyuserid', 'module', 'lastEditedByUserId', 'Last editor', 'text', TRUE, TRUE, 'system-user'),
  ('fld-module-lasteditedat', 'module', 'lastEditedAt', 'Last edited at', 'text', TRUE, TRUE, 'system-user'),

  ('fld-splice-family', 'splice', 'family', 'Family', 'text', TRUE, TRUE, 'system-user'),
  ('fld-splice-isactive', 'splice', 'isActive', 'Active', 'text', TRUE, TRUE, 'system-user'),
  ('fld-splice-stockstatus', 'splice', 'stockStatus', 'Stock status', 'text', TRUE, FALSE, 'system-user'),
  ('fld-splice-compatibilityhints', 'splice', 'compatibilityHints', 'Compatibility hints', 'text', TRUE, FALSE, 'system-user'),
  ('fld-splice-createdbyuserid', 'splice', 'createdByUserId', 'Created by', 'text', TRUE, TRUE, 'system-user'),
  ('fld-splice-createdat', 'splice', 'createdAt', 'Created at', 'text', TRUE, TRUE, 'system-user'),
  ('fld-splice-isreviewed', 'splice', 'isReviewed', 'Reviewed', 'text', TRUE, TRUE, 'system-user'),
  ('fld-splice-reviewedbyuserid', 'splice', 'reviewedByUserId', 'Reviewed by', 'text', TRUE, TRUE, 'system-user'),
  ('fld-splice-reviewedat', 'splice', 'reviewedAt', 'Reviewed at', 'text', TRUE, TRUE, 'system-user'),
  ('fld-splice-lasteditedbyuserid', 'splice', 'lastEditedByUserId', 'Last editor', 'text', TRUE, TRUE, 'system-user'),
  ('fld-splice-lasteditedat', 'splice', 'lastEditedAt', 'Last edited at', 'text', TRUE, TRUE, 'system-user')
ON CONFLICT (category, key) DO NOTHING;
